import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { Archive, ArrowUpRight, BookOpen, Check, ChevronDown, FileText, Hash, LayoutGrid, Link2, LoaderCircle, LogOut, Menu, MessageCircle, MoreHorizontal, Plus, Search, Share2, Sparkles, Trash2, Video, X } from 'lucide-react'
import './App.css'

type Content = { _id: string; title?: string; link?: string; type?: string; tags?: string[]; createdAt?: string }
const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:3000'
const sampleNotes: Content[] = [
  { _id: 'sample-1', type: 'Document', title: "Aarav's Future Projects", link: 'Build a personal knowledge base\nCreate a morning habit tracker\nDesign a minimalist todo app', tags: ['productivity', 'ideas'], createdAt: '10/03/2024' },
  { _id: 'sample-2', type: 'Video', title: 'Priya on Building a Second Brain', link: 'https://www.youtube.com/watch?v=example', tags: ['productivity', 'learning'], createdAt: '09/03/2024' },
  { _id: 'sample-3', type: 'Tweets', title: "Meera's Productivity Tip", link: 'The best way to learn is to build in public. Share your progress, get feedback, and help others along the way.', tags: ['productivity', 'learning'], createdAt: '08/03/2024' },
]

function App() {
  const [token, setToken] = useState(() => localStorage.getItem('second-brain-token'))
  const [notes, setNotes] = useState<Content[]>([])
  const [query, setQuery] = useState('')
  const [activeType, setActiveType] = useState('All notes')
  const [authMode, setAuthMode] = useState<'signin' | 'signup'>('signin')
  const [showAdd, setShowAdd] = useState(false)
  const [showSidebar, setShowSidebar] = useState(false)
  const [loading, setLoading] = useState(false)
  const [notice, setNotice] = useState('')
  useEffect(() => { if (token) void loadNotes() }, [token])
  async function loadNotes() { setLoading(true); try { const response = await fetch(`${API_URL}/api/v1/content`, { headers: { Authorization: token ?? '' } }); if (!response.ok) throw new Error(); const data = await response.json(); setNotes(data.content ?? []) } catch { setNotice('The API is unavailable, so you are viewing demo notes.'); setNotes(sampleNotes) } finally { setLoading(false) } }
  function signOut() { localStorage.removeItem('second-brain-token'); setToken(null); setNotes([]) }
  const filteredNotes = useMemo(() => notes.filter((note) => { const searchable = `${note.title ?? ''} ${note.link ?? ''} ${note.tags?.join(' ') ?? ''}`.toLowerCase(); return searchable.includes(query.toLowerCase()) && (activeType === 'All notes' || note.type?.toLowerCase() === activeType.toLowerCase()) }), [activeType, notes, query])
  if (!token) return <AuthScreen mode={authMode} setMode={setAuthMode} onAuthenticated={(newToken) => { localStorage.setItem('second-brain-token', newToken); setToken(newToken) }} />
  return <div className="app-shell">
    <Sidebar activeType={activeType} setActiveType={setActiveType} open={showSidebar} close={() => setShowSidebar(false)} signOut={signOut} />
    <main className="main-content">
      <header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setShowSidebar(true)}><Menu size={20} /></button><div className="crumb"><span>Workspace</span><ChevronDown size={15} /><strong>All notes</strong></div><div className="top-actions"><button className="share-button" onClick={async () => { const response = await fetch(`${API_URL}/api/v1/brain/share`, { method: 'POST', headers: { Authorization: token ?? '', 'Content-Type': 'application/json' }, body: JSON.stringify({ share: true }) }); const data = await response.json(); if (data.hash) { await navigator.clipboard?.writeText(`${window.location.origin}/share/${data.hash}`); setNotice('Share link copied to clipboard.') } }}><Share2 size={16} /> Share brain</button><button className="primary-button" onClick={() => setShowAdd(true)}><Plus size={17} /> Add content</button><button className="icon-button"><MoreHorizontal size={20} /></button></div></header>
      <section className="content-area"><div className="page-heading"><div><p className="eyebrow"><Sparkles size={13} /> YOUR PERSONAL KNOWLEDGE SPACE</p><h1>All notes</h1><p className="subtitle">Keep the ideas worth coming back to.</p></div><div className="stats"><span>{notes.length || 3} notes</span><span className="stat-dot" /><span>Updated just now</span></div></div><div className="toolbar"><label className="search-box"><Search size={17} /><input placeholder="Search your brain..." value={query} onChange={(event) => setQuery(event.target.value)} /><kbd>⌘ K</kbd></label><div className="view-controls"><button className="filter-button"><Archive size={15} /> Recent <ChevronDown size={14} /></button><button className="view-button active" aria-label="Grid view"><LayoutGrid size={17} /></button><button className="view-button" aria-label="List view"><FileText size={17} /></button></div></div>{notice && <div className="notice"><Check size={16} /> {notice} <button onClick={() => setNotice('')} aria-label="Dismiss"><X size={14} /></button></div>}{loading ? <div className="empty-state"><LoaderCircle className="spin" size={28} /><p>Loading your notes...</p></div> : filteredNotes.length ? <div className="note-grid">{filteredNotes.map((note, index) => <NoteCard key={note._id} note={note} index={index} onDelete={async () => { await fetch(`${API_URL}/api/v1/content`, { method: 'DELETE', headers: { Authorization: token ?? '', 'Content-Type': 'application/json' }, body: JSON.stringify({ contentId: note._id }) }); setNotes((current) => current.filter((item) => item._id !== note._id)) }} />)}</div> : <div className="empty-state"><BookOpen size={32} /><h2>No notes found</h2><p>Try another search or add a new piece of knowledge.</p><button className="primary-button" onClick={() => setShowAdd(true)}><Plus size={17} /> Add your first note</button></div>}</section>
    </main>{showAdd && <AddModal token={token} onClose={() => setShowAdd(false)} onAdded={(note) => { setNotes((current) => [note, ...current]); setShowAdd(false); setNotice('Note added to your brain.') }} />}
  </div>
}

function Sidebar({ activeType, setActiveType, open, close, signOut }: { activeType: string; setActiveType: (value: string) => void; open: boolean; close: () => void; signOut: () => void }) { const items = [{ label: 'All notes', icon: LayoutGrid }, { label: 'Tweets', icon: MessageCircle }, { label: 'Videos', icon: Video }, { label: 'Documents', icon: FileText }, { label: 'Links', icon: Link2 }, { label: 'Tags', icon: Hash }]; return <aside className={`sidebar ${open ? 'open' : ''}`}><div className="brand"><span className="brand-mark"><Sparkles size={18} /></span><span>Second Brain</span><button className="icon-button close-sidebar" onClick={close} aria-label="Close navigation"><X size={19} /></button></div><div className="sidebar-label">LIBRARY</div><nav>{items.map(({ label, icon: Icon }) => <button key={label} className={activeType === label ? 'nav-item active' : 'nav-item'} onClick={() => { setActiveType(label); close() }}><Icon size={17} /><span>{label}</span>{label === 'All notes' && <span className="nav-count">12</span>}</button>)}</nav><div className="sidebar-bottom"><div className="upgrade"><Sparkles size={16} /><div><strong>Make space for good ideas</strong><span>Capture more, remember more.</span></div><ArrowUpRight size={15} /></div><button className="profile" onClick={signOut}><span className="avatar">AS</span><span><strong>Ananya Sharma</strong><small>Personal workspace</small></span><LogOut size={16} /></button></div></aside> }

function NoteCard({ note, index, onDelete }: { note: Content; index: number; onDelete: () => void }) { const type = note.type ?? 'Document'; const lines = note.link?.split('\n').filter(Boolean) ?? []; return <article className="note-card" style={{ animationDelay: `${index * 70}ms` }}><div className="card-top"><span className={`type-icon ${type.toLowerCase()}`}><TypeIcon type={type} /></span><span className="card-type">{type}</span><div className="card-actions"><button aria-label="Share note"><Share2 size={14} /></button><button aria-label="Delete note" onClick={onDelete}><Trash2 size={14} /></button></div></div><h2>{note.title || 'Untitled note'}</h2>{type === 'Video' ? <div className="video-preview"><Video size={24} /><span>Watch saved video</span><ArrowUpRight size={16} /></div> : <div className="note-body">{lines.map((line) => <p key={line}>{type === 'Document' && <span className="bullet">•</span>}{line}</p>)}</div>}<div className="card-footer"><div className="tags">{(note.tags?.length ? note.tags : ['personal']).map((tag) => <span key={tag}>#{tag}</span>)}</div><small>Added on {note.createdAt ?? 'today'}</small></div></article> }
function TypeIcon({ type }: { type: string }) { if (type === 'Tweets') return <MessageCircle size={13} />; if (type === 'Video') return <Video size={13} />; if (type === 'Links') return <Link2 size={13} />; return <FileText size={13} /> }

function AuthScreen({ mode, setMode, onAuthenticated }: { mode: 'signin' | 'signup'; setMode: (mode: 'signin' | 'signup') => void; onAuthenticated: (token: string) => void }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(`${API_URL}/api/v1/${mode}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? 'Something went wrong'); if (mode === 'signin') onAuthenticated(data.token); else { setMode('signin'); setError('Your brain is ready. Sign in to continue.') } } catch (err) { setError(err instanceof Error ? err.message : 'Unable to connect to the backend.') } finally { setBusy(false) } } return <div className="auth-page"><div className="auth-orbit orbit-one" /><div className="auth-orbit orbit-two" /><div className="auth-card"><div className="brand auth-brand"><span className="brand-mark"><Sparkles size={19} /></span><span>Second Brain</span></div><div className="auth-copy"><p className="eyebrow"><Sparkles size={13} /> A HOME FOR YOUR IDEAS</p><h1>Think less.<br /><em>Remember more.</em></h1><p>Save the sparks, links, and lessons that make you who you are.</p></div><form onSubmit={submit}><label>Username<input required value={username} onChange={(event) => setUsername(event.target.value)} placeholder="ananya" /></label><label>Password<input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="8+ characters" /></label>{error && <p className="form-message">{error}</p>}<button className="primary-button full-width" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : mode === 'signin' ? 'Enter your brain' : 'Create your brain'} {!busy && <ArrowUpRight size={17} />}</button></form><p className="auth-switch">{mode === 'signin' ? 'New here?' : 'Already have a brain?'} <button onClick={() => { setMode(mode === 'signin' ? 'signup' : 'signin'); setError('') }}>{mode === 'signin' ? 'Create an account' : 'Sign in'}</button></p></div><p className="auth-footer">Private by default · Built for thinking clearly</p></div> }

function AddModal({ token, onClose, onAdded }: { token: string | null; onClose: () => void; onAdded: (note: Content) => void }) { const [title, setTitle] = useState(''); const [link, setLink] = useState(''); const [type, setType] = useState('Document'); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); const response = await fetch(`${API_URL}/api/v1/content`, { method: 'POST', headers: { Authorization: token ?? '', 'Content-Type': 'application/json' }, body: JSON.stringify({ title, link, type }) }); if (response.ok) onAdded({ _id: crypto.randomUUID(), title, link, type, tags: ['personal'], createdAt: 'today' }); setBusy(false) } return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="modal" onSubmit={submit}><div className="modal-header"><div><p className="eyebrow">CAPTURE A THOUGHT</p><h2>Add content</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><X size={19} /></button></div><label>Title<input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What do you want to remember?" autoFocus /></label><label>Type<select value={type} onChange={(event) => setType(event.target.value)}><option>Document</option><option>Tweets</option><option>Video</option><option>Links</option></select></label><label>Note or link<textarea required value={link} onChange={(event) => setLink(event.target.value)} placeholder="Add the useful bit here..." rows={5} /></label><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : <Plus size={17} />} Save note</button></div></form></div> }

export default App
